version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install  # This installs your Node.js app dependencies.

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      # Log in to ECR using AWS CLI. Replace <your-region> and <account_id> with actual values.
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 467461513525.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      # Build the Docker image with the tag "weather-app"
      - docker build -t weather-app .
      # Tag the image so it can be pushed to ECR
      - docker tag weather-app:latest 467461513525.dkr.ecr.ap-south-1.amazonaws.com/weather-app:latest
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      # Push the tagged Docker image to your ECR repository
      -docker push 467461513525.dkr.ecr.ap-south-1.amazonaws.com/weather-app:latest

artifacts:
  files:
    - '**/*'  # This will include all files in the repository. You can modify it if needed.
